#!/bin/sh

# Note: this script was written before the POW was added

client="ncat hashconsulting.hackthe.vote 50007"
for x in $(seq 1 100); do echo $x; echo | $client | sed -e 's/$/:ahNgah7d/' >> hashes.txt; done
hashcat -m 10 hashes.txt /usr/share/dict/words
hashcat -m 10 hashes.txt --show | cut -d: -f3 | sort -u > recovered_dictionary.txt
# now manually edit out words that are in other words
# e.g. if it contains "overthrow", "throws", and "overthrows", remove "throws"
# and "overthrow", because they were most likely generated by rules that delete
# parts of the word
